---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "app"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "app"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
