services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - "./resources/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "app-static:/usr/share/nginx/html/static/"

  app:
    build:
      context: app
    restart: always
    environment:
      - "SQL_HOST=postgres"
      - "SQL_USER=postgres"
      - "SQL_PASSWORD=s3cR3tDj4ng0ApP"
      - "SQL_DATABASE=app"
      - "ALLOWED_HOSTS=app"
      - "DEBUG=1"
      - "PUBLIC_URL=http://127.0.0.1:8080"
    volumes:
      - "app-static:/home/app/web/static"

  postgres:
    image: postgres
    restart: always
    environment:
      - "POSTGRES_PASSWORD=s3cR3tDj4ng0ApP"
      - "POSTGRES_DB=app"
    volumes:
      - "postgres-data:/var/lib/postgres/data"

volumes:
  app-static:
  postgres-data:
